// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceOne.proto

package ds.project.smarthealth;

public interface BMIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealth.BMIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string answer = 1;</code>
   */
  java.lang.String getAnswer();
  /**
   * <code>string answer = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnswerBytes();
}
