// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceOne.proto

package ds.project.smarthealth;

public interface BMIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealth.BMIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 weight = 1;</code>
   */
  int getWeight();

  /**
   * <code>float height = 2;</code>
   */
  float getHeight();
}
