// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceOne.proto

package ds.project.smarthealth;

public interface BMIRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealth.BMIRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weight = 1;</code>
   */
  double getWeight();

  /**
   * <code>double height = 2;</code>
   */
  double getHeight();

  /**
   * <code>.smarthealth.BMIRequest.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.smarthealth.BMIRequest.Operation operation = 3;</code>
   */
  ds.project.smarthealth.BMIRequest.Operation getOperation();
}
