// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceOne.proto

package ds.project.smarthealth;

public final class SmartHealthImp {
  private SmartHealthImp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthealth_BMIRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthealth_BMIRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthealth_BMIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthealth_BMIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020serviceOne.proto\022\013smarthealth\"}\n\nBMIRe" +
      "quest\022\016\n\006weight\030\001 \001(\001\022\016\n\006height\030\002 \001(\001\0224\n" +
      "\toperation\030\003 \001(\0162!.smarthealth.BMIReques" +
      "t.Operation\"\031\n\tOperation\022\014\n\010DIVISION\020\000\"\036" +
      "\n\013BMIResponse\022\017\n\007message\030\001 \001(\t2J\n\tSmarth" +
      "App\022=\n\006sayBMI\022\027.smarthealth.BMIRequest\032\030" +
      ".smarthealth.BMIResponse\"\000B*\n\026ds.project" +
      ".smarthealthB\016SmartHealthImpP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarthealth_BMIRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarthealth_BMIRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthealth_BMIRequest_descriptor,
        new java.lang.String[] { "Weight", "Height", "Operation", });
    internal_static_smarthealth_BMIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarthealth_BMIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthealth_BMIResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
