// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceOne.proto

package ds.project.smarthealth;

public interface ValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealth.ValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
