// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceOne.proto

package ds.project.smarthealth;

public interface ValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealth.ValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string speciality = 1;</code>
   */
  java.lang.String getSpeciality();
  /**
   * <code>string speciality = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpecialityBytes();
}
