// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceOne.proto

package ds.project.smarthealth;

public interface ValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealth.ValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string medicine = 1;</code>
   */
  java.lang.String getMedicine();
  /**
   * <code>string medicine = 1;</code>
   */
  com.google.protobuf.ByteString
      getMedicineBytes();

  /**
   * <code>int32 number = 2;</code>
   */
  int getNumber();
}
