// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceTwo.proto

package ds.project.two.smarthealthtwo;

public interface FatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealthtwo.FatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double percentage = 1;</code>
   */
  double getPercentage();
}
