// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceTwo.proto

package ds.project.two.smarthealthtwo;

public interface FatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealthtwo.FatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float bmi = 1;</code>
   */
  float getBmi();

  /**
   * <code>float age = 2;</code>
   */
  float getAge();
}
