// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceTwo.proto

package ds.project.two.smarthealthtwo;

public final class SmartHealthTwoImp {
  private SmartHealthTwoImp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthealthtwo_ValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthealthtwo_ValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthealthtwo_ValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthealthtwo_ValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthealthtwo_FatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthealthtwo_FatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smarthealthtwo_FatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smarthealthtwo_FatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020serviceTwo.proto\022\016smarthealthtwo\"\"\n\014Va" +
      "lueRequest\022\022\n\nspeciality\030\001 \001(\t\"\037\n\rValueR" +
      "esponse\022\016\n\006number\030\001 \001(\005\"&\n\nFatRequest\022\013\n" +
      "\003bmi\030\001 \001(\002\022\013\n\003age\030\002 \001(\002\"!\n\013FatResponse\022\022" +
      "\n\npercentage\030\001 \001(\0012\261\001\n\017SmarthHealthTwo\022Q" +
      "\n\016sendValuesBack\022\034.smarthealthtwo.ValueR" +
      "equest\032\035.smarthealthtwo.ValueResponse\"\0000" +
      "\001\022K\n\014calculateFAT\022\032.smarthealthtwo.FatRe" +
      "quest\032\033.smarthealthtwo.FatResponse\"\000(\001B4" +
      "\n\035ds.project.two.smarthealthtwoB\021SmartHe" +
      "althTwoImpP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smarthealthtwo_ValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smarthealthtwo_ValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthealthtwo_ValueRequest_descriptor,
        new java.lang.String[] { "Speciality", });
    internal_static_smarthealthtwo_ValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smarthealthtwo_ValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthealthtwo_ValueResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_smarthealthtwo_FatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smarthealthtwo_FatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthealthtwo_FatRequest_descriptor,
        new java.lang.String[] { "Bmi", "Age", });
    internal_static_smarthealthtwo_FatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smarthealthtwo_FatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smarthealthtwo_FatResponse_descriptor,
        new java.lang.String[] { "Percentage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
