// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceTwo.proto

package ds.project.two.smarthealthtwo;

public interface ValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealthtwo.ValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
