// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serviceTwo.proto

package ds.project.two.smarthealthtwo;

public interface ValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smarthealthtwo.ValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string speciality = 1;</code>
   */
  java.lang.String getSpeciality();
  /**
   * <code>string speciality = 1;</code>
   */
  com.google.protobuf.ByteString
      getSpecialityBytes();
}
